name: Deploy

on:
  workflow_run:
    workflows:
      - "Terraform apply"
    types:
      - completed

jobs:
  build:
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: git lfs pull
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: us-east-1
      
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Build and Deploy
        working-directory: app
        run: |
          npm install -g pnpm
          pnpm install --no-frozen-lockfile
          pnpm build
      
      - name: Deploy to S3
        env:
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        run: |
          aws s3 sync app/.vitepress/dist s3://$S3_BUCKET_NAME --delete
          aws s3 sync statics s3://$S3_BUCKET_NAME 
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

      


